/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my accounts
         * @description Returns the accounts the authenticated user is a member of, each annotated with the caller's role. Paginated.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (max 100) */
                    limit?: number;
                    /** @description Items to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListAccountsResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an account
         * @description Returns the account if the caller is a member. Non-members get 404 (existence is not leaked).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account identifier */
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountWithRole"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename an account
         * @description Renames the account. Only owner/admin members may. Non-members get 404 (no existence leak); members lacking the role get 403.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account identifier */
                    accountId: string;
                };
                cookie?: never;
            };
            /** @description Account fields that can be changed */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountWithRole"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List account members
         * @description Lists the members of the account (user id, email, role). Visible to members only; non-members get 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account identifier */
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListMembersResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a user with a securely hashed password and returns a JWT.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Registration credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterBody"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Verifies credentials and returns a JWT on success.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Login credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List crops
         * @description Lists the crop catalog (global reference data). Paginated.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (max 100) */
                    limit?: number;
                    /** @description Items to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListCropsResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops/{cropId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a crop with its targets
         * @description Returns a crop and its ideal value ranges per metric.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Crop identifier */
                    cropId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CropWithTargets"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my devices
         * @description Lists devices the caller can see: devices across all accounts they are a member of, UNION devices shared with them (read-only). Optional ?accountId= restricts to one account the caller belongs to (non-member → 404) and excludes shared-only devices. Paginated; soft-deleted devices are excluded; deduped.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Restrict to devices in this account (caller must be a member) */
                    accountId?: string;
                    /** @description Page size (max 100) */
                    limit?: number;
                    /** @description Items to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListDevicesResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Register a device
         * @description Claims a device under an account. Caller must be owner/admin of the account (non-members get 404). Returns the device plus a one-time plaintext device secret — store it now, it is never returned again.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Register/claim a device under an account */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterDeviceBody"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceRegisteredResponse"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a device
         * @description Returns the device if the caller is read-capable — a member of its account OR a sharee. Others (and missing/soft-deleted devices) get 404 — existence is not leaked. Never includes the device secret.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafeDevice"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a device
         * @description Soft-deletes the device (sets deleted_at; history is retained). Only owner/admin of the account may. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Device deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a device
         * @description Updates name/firmwareVersion. Only owner/admin of the device's account may. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            /** @description Device fields that can be changed */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDeviceBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafeDevice"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer a device
         * @description Reassigns the device to another account. Caller must be owner/admin of BOTH the device's current account and the destination account. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            /** @description Reassign a device to another account */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransferDeviceBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafeDevice"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/grow-sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a device's grow sites
         * @description Lists live (non-soft-deleted) grow sites of a device. Any read-capable caller (a member of the device's account or a sharee) may read; others get 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListGrowSitesResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a grow site
         * @description Adds a grow site (slot position) to a device. Owner/admin of the device's account only. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404. Duplicate position on the same device → 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            /** @description Create a grow site under a device */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGrowSiteBody"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafeGrowSite"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a device's readings
         * @description Time-range query over a device's readings. Any read-capable caller (a member of the device's account or a sharee) may read; others (and missing/soft-deleted devices) get 404. Ordered newest-first by recorded_at, served by the composite PK. Optional ?metric= (code), ?from=/?to= (ISO), ?limit= (default 100, max 1000).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter to one metric code */
                    metric?: string;
                    from?: string;
                    to?: string;
                    /** @description Page size (max 1000) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListReadingsResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a device's events
         * @description Time-range query over a device's actuator/system events. Any read-capable caller (a member of the device's account or a sharee) may read; others get 404. Ordered newest-first by recorded_at. Optional ?from=/?to= (ISO), ?limit= (default 100, max 1000).
         */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    /** @description Page size (max 1000) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEventsResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a device's shares
         * @description Lists who a device is shared with (grantee id/email/role). Only owner/admin of the device's account may. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListSharesResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Share a device
         * @description Grants a user read-only (viewer/follower) access to a device. Only owner/admin of the device's account may. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404. Unknown grantee email → 404. Sharing to a user who is already a member of the device's account → 409 (redundant). Duplicate share → 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                };
                cookie?: never;
            };
            /** @description Grant a user read-only access to a device */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateShareBody"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafeShare"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{deviceId}/shares/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a device share
         * @description Revokes a share (the grantee loses access). Only owner/admin of the device's account may. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404. An unknown share id on a manageable device → 404.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Device identifier */
                    deviceId: string;
                    /** @description Share identifier */
                    shareId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Share revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grow-sites/{growSiteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a grow site
         * @description Returns the grow site if the caller is read-capable on its device — a member of the device's account OR a sharee. Others (and missing/soft-deleted grow sites) get 404 — existence is not leaked.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Grow-site identifier */
                    growSiteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafeGrowSite"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a grow site
         * @description Soft-deletes the grow site (sets deleted_at; history is retained). Only owner/admin of the device's account may. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Grow-site identifier */
                    growSiteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Grow site deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a grow site
         * @description Updates the grow site name. Only owner/admin of the device's account may. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Grow-site identifier */
                    growSiteId: string;
                };
                cookie?: never;
            };
            /** @description Grow-site fields that can be changed */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateGrowSiteBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafeGrowSite"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/grow-sites/{growSiteId}/plantings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a grow site's plantings
         * @description Lists the grow site's planting history (newest first). Any read-capable caller (a member of the device's account or a sharee) may read; others get 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Grow-site identifier */
                    growSiteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListPlantingsResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Start a planting
         * @description Starts a planting of a crop in the grow site. Owner/admin only. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404. Unknown cropCode → 400. At most one active planting per grow site — starting a second while one is active → 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Grow-site identifier */
                    growSiteId: string;
                };
                cookie?: never;
            };
            /** @description Start a planting in a grow site */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartPlantingBody"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafePlanting"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of readings
         * @description Device-authenticated (X-Device-Serial + X-Device-Secret). Stores a batch of sensor readings idempotently — duplicate (recorded_at, metric) rows for the device are skipped via the composite PK. Updates last_seen_at and marks the device active. Unknown metric code, or grow-site/planting not belonging to this device, → 400.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Batch of readings from a device */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngestReadingsBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestReadingsResult"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of device events
         * @description Device-authenticated (X-Device-Serial + X-Device-Secret). Appends actuator/system events for the device and updates last_seen_at. Events are not deduplicated (each has a surrogate id).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Batch of events from a device */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngestEventsBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestEventsResult"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plantings/{plantingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * End a planting
         * @description Ends/harvests an active planting: sets a terminal status ('harvested'|'failed'|'ended') and ended_at (defaults to now). Owner/admin only. Read-capable callers (plain members or sharees) get 403; callers with no capability get 404. Re-ending an already-ended planting → 409.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Planting identifier */
                    plantingId: string;
                };
                cookie?: never;
            };
            /** @description End/harvest a planting */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePlantingBody"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafePlanting"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Account fields that can be changed */
        UpdateAccountBody: {
            /**
             * @description New account name
             * @example Acme Farms
             */
            name: string;
        };
        /** @description Registration credentials */
        RegisterBody: {
            /**
             * Format: email
             * @description User email address (trimmed + lowercased)
             * @example user@example.com
             */
            email: string;
            /**
             * @description Plain-text password (8–72 characters)
             * @example sup3rsecret
             */
            password: string;
        };
        /** @description Login credentials */
        LoginBody: {
            /**
             * Format: email
             * @description User email address (trimmed + lowercased)
             * @example user@example.com
             */
            email: string;
            /**
             * @description Plain-text password (8–72 characters)
             * @example sup3rsecret
             */
            password: string;
        };
        /** @description Register/claim a device under an account */
        RegisterDeviceBody: {
            /**
             * Format: uuid
             * @description Account identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            accountId: string;
            /**
             * @description Factory serial (immutable, globally unique)
             * @example CAT-000123
             */
            serial: string;
            /**
             * @description Catalog model code
             * @example pot-mini
             */
            deviceModelCode: string;
            /**
             * @description User-facing device label
             * @example Kitchen pot
             */
            name?: string;
            /**
             * @description Reported firmware version
             * @example 1.4.2
             */
            firmwareVersion?: string;
        };
        /** @description Device fields that can be changed */
        UpdateDeviceBody: {
            /**
             * @description User-facing device label
             * @example Kitchen pot
             */
            name?: string;
            /**
             * @description Reported firmware version
             * @example 1.4.2
             */
            firmwareVersion?: string;
        };
        /** @description Reassign a device to another account */
        TransferDeviceBody: {
            /**
             * Format: uuid
             * @description Account to transfer ownership to (caller must be owner/admin of it)
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            toAccountId: string;
        };
        /** @description Create a grow site under a device */
        CreateGrowSiteBody: {
            /**
             * @description Slot index on the device
             * @example 0
             */
            position: number;
            /**
             * @description User-facing grow-site label
             * @example Front-left slot
             */
            name?: string;
        };
        /** @description Grant a user read-only access to a device */
        CreateShareBody: {
            /**
             * Format: email
             * @description Email of the user to share with
             * @example friend@example.com
             */
            granteeEmail: string;
            /**
             * @description Share role (defaults to viewer)
             * @example viewer
             * @enum {string}
             */
            role?: "viewer" | "follower";
        };
        /** @description Grow-site fields that can be changed */
        UpdateGrowSiteBody: {
            /**
             * @description User-facing grow-site label
             * @example Front-left slot
             */
            name?: string;
        };
        /** @description Start a planting in a grow site */
        StartPlantingBody: {
            /**
             * @description Catalog crop code (slug)
             * @example basil
             */
            cropCode: string;
            /**
             * Format: date-time
             * @description When the planting started (defaults to now)
             * @example 2026-05-30T12:00:00.000Z
             */
            startedAt?: string;
            /**
             * @description Free-text notes
             * @example Strong early growth.
             */
            notes?: string;
        };
        /** @description Batch of readings from a device */
        IngestReadingsBody: {
            /** @description Batch of readings (1–1000) */
            readings: components["schemas"]["ReadingInput"][];
        };
        /** @description A single sensor reading to ingest */
        ReadingInput: {
            /**
             * @description Catalog metric code
             * @example temp
             */
            metricCode: string;
            /**
             * Format: date-time
             * @description Device clock — when the value was measured
             * @example 2026-05-30T12:00:00.000Z
             */
            recordedAt: string;
            /**
             * @description Measured numeric value
             * @example 23.5
             */
            value: number;
            /**
             * Format: uuid
             * @description Grow-site tag (must belong to this device)
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            growSiteId?: string;
            /**
             * Format: uuid
             * @description Planting tag (must belong to this device)
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            plantingId?: string;
        };
        /** @description Batch of events from a device */
        IngestEventsBody: {
            /** @description Batch of events (1–1000) */
            events: components["schemas"]["EventInput"][];
        };
        /** @description A single device event to ingest */
        EventInput: {
            /**
             * @description Event type
             * @example pump_on
             */
            eventType: string;
            /**
             * Format: date-time
             * @description Device clock — when the event occurred
             * @example 2026-05-30T12:00:00.000Z
             */
            recordedAt: string;
            /**
             * @description Arbitrary event payload
             * @example {
             *       "durationMs": 5000
             *     }
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** @description End/harvest a planting */
        UpdatePlantingBody: {
            /**
             * @description Terminal status to end the planting with
             * @example harvested
             * @enum {string}
             */
            status: "harvested" | "failed" | "ended";
            /**
             * Format: date-time
             * @description When the planting ended (defaults to now)
             * @example 2026-05-30T12:00:00.000Z
             */
            endedAt?: string;
            /**
             * @description Free-text notes
             * @example Strong early growth.
             */
            notes?: string;
        };
        /** @description Paginated list of accounts */
        ListAccountsResponse: {
            data: components["schemas"]["AccountWithRole"][];
            /**
             * @description Total matching accounts
             * @example 1
             */
            total: number;
            /**
             * @description Page size used
             * @example 20
             */
            limit: number;
            /**
             * @description Offset used
             * @example 0
             */
            offset: number;
        };
        /** @description An account the caller is a member of, with the caller's role */
        AccountWithRole: {
            /**
             * Format: uuid
             * @description Account identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * @description Display name
             * @example Ignacio's home
             */
            name: string;
            /**
             * @description Account segment
             * @example personal
             * @enum {string}
             */
            kind: "personal" | "household" | "commercial" | "industrial";
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last-update timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            updatedAt: string;
            /**
             * @description Caller's role on the account
             * @example owner
             * @enum {string}
             */
            role: "owner" | "admin" | "member";
        };
        /** @description Standard error envelope */
        ErrorResponse: {
            /** @example 400 */
            statusCode: number;
            /** @example Bad Request */
            error: string;
            /** @example Invalid email or password */
            message: string;
        };
        /** @description Paginated list of account members */
        ListMembersResponse: {
            data: components["schemas"]["MemberView"][];
            /**
             * @description Total members
             * @example 1
             */
            total: number;
            /**
             * @description Page size used
             * @example 20
             */
            limit: number;
            /**
             * @description Offset used
             * @example 0
             */
            offset: number;
        };
        /** @description A member of an account */
        MemberView: {
            /**
             * Format: uuid
             * @description User identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            userId: string;
            /**
             * Format: email
             * @description Member email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Caller's role on the account
             * @example owner
             * @enum {string}
             */
            role: "owner" | "admin" | "member";
        };
        /** @description Successful authentication result */
        AuthResponse: {
            /**
             * @description Signed JWT access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIuLi4ifQ.signature
             */
            token: string;
            user: components["schemas"]["SafeUser"];
        };
        /** @description User fields safe to expose (never the password) */
        SafeUser: {
            /**
             * Format: uuid
             * @description User identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * Format: email
             * @description User email address
             * @example user@example.com
             */
            email: string;
        };
        /** @description Paginated list of crops */
        ListCropsResponse: {
            data: components["schemas"]["SafeCrop"][];
            /**
             * @description Total crops
             * @example 3
             */
            total: number;
            /**
             * @description Page size used
             * @example 20
             */
            limit: number;
            /**
             * @description Offset used
             * @example 0
             */
            offset: number;
        };
        /** @description A crop catalog entry */
        SafeCrop: {
            /**
             * Format: uuid
             * @description Crop identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * @description Catalog crop code (slug)
             * @example basil
             */
            code: string;
            /**
             * @description Display name
             * @example Basil
             */
            name: string;
        };
        /** @description A crop plus its target ranges */
        CropWithTargets: {
            /**
             * Format: uuid
             * @description Crop identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * @description Catalog crop code (slug)
             * @example basil
             */
            code: string;
            /**
             * @description Display name
             * @example Basil
             */
            name: string;
            /** @description Per-metric ideal ranges for this crop */
            targets: components["schemas"]["CropTargetView"][];
        };
        /** @description An ideal value range for one metric of a crop */
        CropTargetView: {
            /**
             * @description Catalog metric code
             * @example temp
             */
            metricCode: string;
            /**
             * @description Measurement unit of the metric
             * @example °C
             */
            unit: string;
            /**
             * @description Ideal range minimum (null if open)
             * @example 20
             */
            minValue: number | null;
            /**
             * @description Ideal range maximum (null if open)
             * @example 28
             */
            maxValue: number | null;
        };
        /** @description A newly registered device, including its one-time device secret */
        DeviceRegisteredResponse: {
            /**
             * Format: uuid
             * @description Device identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * Format: uuid
             * @description Account identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            accountId: string;
            /**
             * Format: uuid
             * @description Catalog model identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            deviceModelId: string;
            /**
             * @description Catalog model code
             * @example pot-mini
             */
            deviceModelCode: string;
            /**
             * @description Factory serial (immutable, globally unique)
             * @example CAT-000123
             */
            serial: string;
            /**
             * @description User-facing device label (null if unset)
             * @example Kitchen pot
             */
            name: string | null;
            /**
             * @description Reported firmware version (null if unknown)
             * @example 1.4.2
             */
            firmwareVersion: string | null;
            /**
             * @description Device lifecycle status
             * @example active
             * @enum {string}
             */
            status: "provisioned" | "active" | "offline" | "retired";
            /**
             * @description Last contact timestamp (null if never seen)
             * @example 2026-05-30T12:00:00.000Z
             */
            lastSeenAt: string | null;
            /**
             * @description When the device was claimed (null if unregistered)
             * @example 2026-05-30T12:00:00.000Z
             */
            registeredAt: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last-update timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            updatedAt: string;
            /**
             * @description Plaintext device secret — shown ONCE at registration; store it now, it cannot be retrieved again
             * @example k3J8x2qP9wYb1nFvR7sLmZ4tH6cD0aUe
             */
            secret: string;
        };
        /** @description Paginated list of devices */
        ListDevicesResponse: {
            data: components["schemas"]["SafeDevice"][];
            /**
             * @description Total matching devices
             * @example 1
             */
            total: number;
            /**
             * @description Page size used
             * @example 20
             */
            limit: number;
            /**
             * @description Offset used
             * @example 0
             */
            offset: number;
        };
        /** @description Device fields safe to expose (never the device secret) */
        SafeDevice: {
            /**
             * Format: uuid
             * @description Device identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * Format: uuid
             * @description Account identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            accountId: string;
            /**
             * Format: uuid
             * @description Catalog model identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            deviceModelId: string;
            /**
             * @description Catalog model code
             * @example pot-mini
             */
            deviceModelCode: string;
            /**
             * @description Factory serial (immutable, globally unique)
             * @example CAT-000123
             */
            serial: string;
            /**
             * @description User-facing device label (null if unset)
             * @example Kitchen pot
             */
            name: string | null;
            /**
             * @description Reported firmware version (null if unknown)
             * @example 1.4.2
             */
            firmwareVersion: string | null;
            /**
             * @description Device lifecycle status
             * @example active
             * @enum {string}
             */
            status: "provisioned" | "active" | "offline" | "retired";
            /**
             * @description Last contact timestamp (null if never seen)
             * @example 2026-05-30T12:00:00.000Z
             */
            lastSeenAt: string | null;
            /**
             * @description When the device was claimed (null if unregistered)
             * @example 2026-05-30T12:00:00.000Z
             */
            registeredAt: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last-update timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            updatedAt: string;
        };
        /** @description Grow-site fields safe to expose */
        SafeGrowSite: {
            /**
             * Format: uuid
             * @description Grow-site identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * Format: uuid
             * @description Owning device identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            deviceId: string;
            /**
             * @description Slot index on the device
             * @example 0
             */
            position: number;
            /**
             * @description User-facing label (null if unset)
             * @example Front-left slot
             */
            name: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last-update timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            updatedAt: string;
        };
        /** @description Paginated list of grow sites */
        ListGrowSitesResponse: {
            data: components["schemas"]["SafeGrowSite"][];
            /**
             * @description Total grow sites
             * @example 1
             */
            total: number;
            /**
             * @description Page size used
             * @example 20
             */
            limit: number;
            /**
             * @description Offset used
             * @example 0
             */
            offset: number;
        };
        /** @description A time-windowed page of readings (newest first) */
        ListReadingsResponse: {
            data: components["schemas"]["SafeReading"][];
            /**
             * @description Page size used
             * @example 100
             */
            limit: number;
            /**
             * @description Lower bound applied (null if unbounded)
             * @example null
             */
            from: string | null;
            /**
             * @description Upper bound applied (null if unbounded)
             * @example null
             */
            to: string | null;
        };
        /** @description A stored reading safe to expose */
        SafeReading: {
            /**
             * @description Catalog metric code
             * @example temp
             */
            metricCode: string;
            /**
             * Format: date-time
             * @description Device clock — when measured
             * @example 2026-05-30T12:00:00.000Z
             */
            recordedAt: string;
            /**
             * @description Measured numeric value
             * @example 23.5
             */
            value: number;
            /**
             * @description Grow-site tag (null if untagged)
             * @example null
             */
            growSiteId: string | null;
            /**
             * @description Planting tag (null if untagged)
             * @example null
             */
            plantingId: string | null;
            /**
             * Format: date-time
             * @description Ingest clock — when stored
             * @example 2026-05-30T12:00:00.000Z
             */
            receivedAt: string;
        };
        /** @description A time-windowed page of device events (newest first) */
        ListEventsResponse: {
            data: components["schemas"]["SafeDeviceEvent"][];
            /**
             * @description Page size used
             * @example 100
             */
            limit: number;
            /**
             * @description Lower bound applied (null if unbounded)
             * @example null
             */
            from: string | null;
            /**
             * @description Upper bound applied (null if unbounded)
             * @example null
             */
            to: string | null;
        };
        /** @description A stored device event safe to expose */
        SafeDeviceEvent: {
            /**
             * Format: uuid
             * @description Event identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * @description Event type
             * @example pump_on
             */
            eventType: string;
            /**
             * @description Arbitrary event payload
             * @example {
             *       "durationMs": 5000
             *     }
             */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Device clock — when the event occurred
             * @example 2026-05-30T12:00:00.000Z
             */
            recordedAt: string;
            /**
             * Format: date-time
             * @description Ingest clock — when stored
             * @example 2026-05-30T12:00:00.000Z
             */
            receivedAt: string;
        };
        /** @description A device share safe to expose */
        SafeShare: {
            /**
             * Format: uuid
             * @description Share identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * Format: uuid
             * @description Shared device identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            deviceId: string;
            /**
             * Format: uuid
             * @description User the device is shared with
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            granteeUserId: string;
            /**
             * Format: email
             * @description Email of the grantee
             * @example friend@example.com
             */
            granteeEmail: string;
            /**
             * @description Share role (read-only either way)
             * @example viewer
             * @enum {string}
             */
            role: "viewer" | "follower";
            /**
             * Format: date-time
             * @description When the share was granted
             * @example 2026-05-30T12:00:00.000Z
             */
            createdAt: string;
        };
        /** @description Shares on a device */
        ListSharesResponse: {
            data: components["schemas"]["SafeShare"][];
            /**
             * @description Total shares on this device
             * @example 1
             */
            total: number;
        };
        /** @description Planting fields safe to expose */
        SafePlanting: {
            /**
             * Format: uuid
             * @description Planting identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            id: string;
            /**
             * Format: uuid
             * @description Grow-site identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            growSiteId: string;
            /**
             * Format: uuid
             * @description Crop identifier
             * @example 019e71ba-dab0-7eee-8fc2-67038bd23c20
             */
            cropId: string;
            /**
             * @description Catalog crop code (slug)
             * @example basil
             */
            cropCode: string;
            /**
             * @description Planting lifecycle status
             * @example active
             * @enum {string}
             */
            status: "active" | "harvested" | "failed" | "ended";
            /**
             * Format: date-time
             * @description When the planting started
             * @example 2026-05-30T12:00:00.000Z
             */
            startedAt: string;
            /**
             * @description When the planting ended (null while active)
             * @example 2026-06-30T12:00:00.000Z
             */
            endedAt: string | null;
            /**
             * @description Free-text notes (null if none)
             * @example Strong early growth.
             */
            notes: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last-update timestamp
             * @example 2026-05-30T12:00:00.000Z
             */
            updatedAt: string;
        };
        /** @description Paginated list of plantings (newest first) */
        ListPlantingsResponse: {
            data: components["schemas"]["SafePlanting"][];
            /**
             * @description Total plantings
             * @example 1
             */
            total: number;
            /**
             * @description Page size used
             * @example 20
             */
            limit: number;
            /**
             * @description Offset used
             * @example 0
             */
            offset: number;
        };
        /** @description Outcome of an idempotent readings ingest */
        IngestReadingsResult: {
            /**
             * @description Readings in the request
             * @example 10
             */
            received: number;
            /**
             * @description New rows stored
             * @example 10
             */
            inserted: number;
            /**
             * @description Rows skipped as duplicates (received − inserted)
             * @example 0
             */
            duplicates: number;
        };
        /** @description Outcome of an events ingest */
        IngestEventsResult: {
            /**
             * @description Events in the request
             * @example 3
             */
            received: number;
            /**
             * @description Events stored
             * @example 3
             */
            inserted: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
